import { NetworkConfig } from '../../../types';

export const defaultNetworks: NetworkConfig[] = [
	{
		id: 'facebook',
		name: 'Facebook',
		label: 'Facebook',
		share_url: 'https://www.facebook.com/sharer/sharer.php?u={url}',
		requires_handle: false,
		icon_class: 'fab fa-facebook-f',
		color: '#1877f2',
	},
	{
		id: 'twitter',
		name: 'Twitter',
		label: 'Twitter',
		share_url: 'https://twitter.com/intent/tweet?url={url}&text={title}',
		requires_handle: false,
		icon_class: 'fab fa-twitter',
		color: '#1da1f2',
	},
	{
		id: 'linkedin',
		name: 'LinkedIn',
		label: 'LinkedIn',
		share_url: 'https://www.linkedin.com/sharing/share-offsite/?url={url}',
		requires_handle: false,
		icon_class: 'fab fa-linkedin-in',
		color: '#0077b5',
	},
	{
		id: 'pinterest',
		name: 'Pinterest',
		label: 'Pinterest',
		share_url:
			'https://pinterest.com/pin/create/button/?url={url}&description={title}',
		requires_handle: false,
		icon_class: 'fab fa-pinterest-p',
		color: '#bd081c',
	},
	{
		id: 'reddit',
		name: 'Reddit',
		label: 'Reddit',
		share_url: 'https://reddit.com/submit?url={url}&title={title}',
		requires_handle: false,
		icon_class: 'fab fa-reddit-alien',
		color: '#ff4500',
	},
	{
		id: 'whatsapp',
		name: 'WhatsApp',
		label: 'WhatsApp',
		share_url: 'https://wa.me/?text={title}%20{url}',
		requires_handle: false,
		icon_class: 'fab fa-whatsapp',
		color: '#25d366',
	},
	{
		id: 'google-plus',
		name: 'Google Plus',
		label: 'Google Plus',
		share_url: 'https://plus.google.com/share?url={url}',
		requires_handle: false,
		icon_class: 'fab fa-google-plus-g',
		color: '#dd4b39',
	},
	{
		id: 'google-bookmarks',
		name: 'Google Bookmarks',
		label: 'Google Bookmarks',
		share_url:
			'https://www.google.com/bookmarks/mark?op=edit&bkmk={url}&title={title}',
		requires_handle: false,
		icon_class: 'fab fa-google',
		color: '#4285f4',
	},
	{
		id: 'email',
		name: 'Email',
		label: 'Email',
		share_url: 'mailto:?subject={title}&body={url}',
		requires_handle: false,
		icon_class: 'fas fa-envelope',
		color: '#666666',
	},
];
